### ISSUE TITLE
trouble using db.pull()

### ISSUE THREAD

**Issue by boxxxie** [dominicbarnes/node-couchdb-api#10]
```
var couchdb = require('couchdb-api');
var user_pass = 'user:pass';
var dealscc = couchdb.srv(user_pass+'@ip','80');
var local_db = couchdb.srv(user_pass+'@localhost')

//local_db.allDbs();
var dbname = 'backoffice_app';
local_db.db(dbname)
    .pull(dealscc.db(dbname),
      function(err,data,resp){
          console.log(err + ' '+ data + ' ' + resp)
      })
```

the above code times out, i'm not sure what i'm doing wrong

**Comment by dominicbarnes** [comment]
I'll test out the `pull` method itself, can you try setting the auth information differently though?

It's not documented on my site yet, sorry about that, but there is an `auth` property on the server object that sets the username/password for the server.

```
dealscc.auth = "user:pass";
// OR
dealscc.auth = [ "user", "pass" ];
```

Try this out before calling pull on your remote server, let me know if it helps!
