### ISSUE TITLE
Migrating node-couchdb-api to node 0.8.8+

### ISSUE THREAD

**Issue by akumpf** [dominicbarnes/node-couchdb-api#14]
We have a handful of apps that are using couchdb (and in particular, the node-couchdb-api module).

Unfortunately, trying to migrate from 0.6 (which worked well) to 0.8 failed. I traced the issue (at least for us) down to how authentication with the couchdb server was being handled. For some reason there was a leading square bracket (`[`) when the url was parsed.

With a little workaround to add in authentication after creation, everything seems to be working fine in 0.8!

Essentially, you just create the database server connection as if there is no authentication, then add the auth param to the server's url setter. Here's what we ended up doing.

```
var dbServer      = couchdb.srv(COUCHDB_HOST, COUCHDB_PORT, false, false);
dbServer.url      = {
  hostname: COUCHDB_HOST,
  port:     COUCHDB_PORT,
  protocol: COUCHDB_HTTP,
  auth:     COUCHDB_AUTH
};
```

We'd love to keep using couchdb and this module, but having things break when moving to the current stable version of node is a bit frustrating. Perhaps there's some MongoDB in our future, but until then hopefully this will help others migrate their couch apps, too. :)

**Comment by dominicbarnes** [comment]
Can you include some more code for me to reproduce your problem? (as of now, my unit tests still run successfully, so I need to know what test cases to add)

What auth scheme are you using with CouchDB?

**Comment by akumpf** [comment]
We're using BasicAuth (username, password).

We originally had something like this:

```
var dbServer      = couchdb.srv("dbUser:s3cr3tpasswurdz@localhost", 5984, false, false);
```

and more detail for the example above, we're now using something like this:

```
var COUCHDB_HTTP  = "http:";
var COUCHDB_HOST  = "127.0.0.1";
var COUCHDB_PORT  = 5984; 
var COUCHDB_AUTH  = "dbUser:s3cr3tpasswurdz";
var dbServer      = couchdb.srv(COUCHDB_HOST, COUCHDB_PORT, false, false);
dbServer.url      = {
  hostname: COUCHDB_HOST,
  port:     COUCHDB_PORT,
  protocol: COUCHDB_HTTP,
  auth:     COUCHDB_AUTH
};
```

I think it comes down to how `url.parse()` works (perhaps that evolved from Node 0.6-0.8?). If that's all it takes -- hopefully we're not missing anything else too big here -- it'd be great to bump the version number in package.json to include 0.8 so we don't have to force the install via npm. :)

**Comment by dominicbarnes** [comment]
The first param of `couchdb.srv()` is supposed to be only the hostname. To add auth, you should use the `auth` property after init. (this is the "supported" method)

```
var dbServer = couchdb.srv(COUCHDB_HOST, COUCHDB_PORT, false, false);
dbServer.auth = COUCHDB_AUTH;
// or even
dbServer.auth = [ COUCHDB_USER, COUCHDB_PASS ];
```

**Comment by akumpf** [comment]
haha. ok. didn't see that documented anywhere (i think your personal site is down, by the way). noted! :)

I guess we just got lucky before and the user/pass we're being handled appropriately within the host param.

I saw a couple other projects in my search that depend on node-couchdb-api and are waiting to migrate to 0.8 because of couchdb-api's dependency on 0.6 in package.json. If there's nothing else holding it back, could be a nice update.

**Comment by dominicbarnes** [comment]
Yeah, my site is down because of problems with my DNS provider (expired, haven't heard from them in months...)

Yeah, I've been meaning to update my documentation, but got interrupted by my site going down. (very seriously considering just using a README here on GitHub, but haven't finished yet)

I'll also try and push a new version to NPM here, I didn't realize this was holding people up. :S

**Comment by dominicbarnes** [comment]
Ok, just published v1.1.5 (only a version bump to allow for node "engine 0.8" in the package.json.

Been a while since my last npm publish, so let me know if it works for you and your team.

**Comment by akumpf** [comment]
excellent! although you might set your package.json engine to something like this so people aren't required to bump to 0.8.

```
"engine" : {
        "node" : ">=0.6.0"
    }
```

**Comment by jlange** [comment]
Hey I'm not sure if this is a result from your latest push, but my previously working version is now failing to start. I'm getting an error stating "require.paths is removed. Use node_modules folders or the NODE_PATH environment variable instead". This is being thrown from the file "couchdb-api@0.9.6/index.js". I'm using node version 0.6.3, any ideas on why this would break all of a sudden?

**Comment by dominicbarnes** [comment]
Hmm, I'm not sure what is happening with your install. It doesn't sound like an error my app would throw in itself.

Try installing the latest couchdb-api (1.1.4) for node 0.6?

**Comment by jlange** [comment]
It appears to be an error with npm as node is erring out on its attempts to extend require.paths. I'll try updated to the new install.

**Comment by jlange** [comment]
Sorry to bother you with my inexperience, but I tried to do an  $ npm update couchdb-api and I was unable to get the new 1.1.4 version. Is there another way to do the update? I'm still fairly new to node.

**Comment by dominicbarnes** [comment]
Well, 1.1.5 is the newest version, 1.1.4 was the last version that was explicitly compatible with 0.6.

Can you look at the node_modules/couchdb-api/package.json and see what the version shows?

Maybe you'll need to clear out the existing module folder, and re-install.

```
rm -r node_modules/couchdb-api
npm install couchdb-api
```

**Comment by jlange** [comment]
I did a complete removal and re-install, and the version that I'm seeing in the package is still 0.9.6.

**Comment by jlange** [comment]
I was able to find the issue, I was missing a required NODE_PATH variable. Thanks for your help, sorry to bug you, my issue just coincided with your latest release. Keep of the good work, I love the module!
