### ISSUE TITLE
Allow doc() instances to be initialized with a JSON string

### ISSUE THREAD

**Issue by mrmarbles** [dominicbarnes/node-couchdb-api#2]
Not so much of an issue as a feature request.  Currently I have a JSON string containing data that I want represented as a couch document.  With the current API that means parsing the JSON string into an object then iterating over every top-level key and setting its value on doc.body like so;

```
 var e = JSON.parse(data);
 var doc = db.doc();
 for (key in e) {
      doc.body[key] = e[key];
 };
```

It would be much more convenient if I could simply do this;

```
 var doc = db.doc(data);  // where 'data' is a JSON string, Buffer containing a JSON string or even a JSON object
```

**Comment by dominicbarnes** [comment]
If you pass a JS object, it will initialize the body of the document as the object you passed. You'll still have to use JSON.parse, but it should work. :)

**Comment by mrmarbles** [comment]
Works!  Thanks!
