### ISSUE TITLE
wrong documentation how to read documents

### ISSUE THREAD

**Issue by matthiasjakel** [dominicbarnes/node-couchdb-api#3]
it is doc.get() instead of doc.read() but documented wrong on your website. would be cool if you fix this. 

http://dominicbarnes.us/node-couchdb-api/api/document.html#read

**Comment by dominicbarnes** [comment]
Ah yes, that must've carried over from an old version. It's been updated :)

**Comment by matthiasjakel** [comment]
thanks!
