### ISSUE TITLE
Raw option

### ISSUE THREAD

**Issue by trueshot** [dominicbarnes/node-couchdb-api#6]
It would be useful to have the option to suppress a JSON parse on data returned from a database.   I want to simply buffer the data and pass it on to others.  If each NODE server that handles this has to decode and then stringify, well it is a lot of work for the server and not what is needed in every case.

**Comment by dominicbarnes** [comment]
I will work on adding an option for getting a Buffer. In the meantime, you can pass `stream: true` in your options hash and you'll get a `ReadableStream` in your callback that should work pretty closely.
