### ISSUE TITLE
problem with uploading streaming attachment

### ISSUE THREAD

**Issue by codehero** [dominicbarnes/node-couchdb-api#7]
The combination of mime-type "application/json" and body ReadableStream results in an attachment containing the following:

{"path":"/tmp/TMPFILE","fd":null,"readable":true,"paused":false,"flags":"r","mode":438,"bufferSize":65536}

I don't think you are suppressing your content handlers when uploading streaming attachments.

**Comment by dominicbarnes** [comment]
Check out v1.1.1, I'm using the `request` module under the hood now rather than managing my own HTTP request utilities. I've also added a test-case for what I believe you were describing. Let me know if I've fixed your problem.
