### ISSUE TITLE
reconnect to changes on continuous feed

### ISSUE THREAD

**Issue by codehero** [dominicbarnes/node-couchdb-api#8]
Presently, the library will disconnect when receiving "last_seq" from couchdb when listening to continuous changes, but it won't reconnect. It would be helpful if it did and save the user some code.

**Comment by dominicbarnes** [comment]
I don't really have a place where I am using such a feature, so I'm probably not going to write the best code to accomplish it. Could you provide an example of what you're having to do currently? Either that or fork the lib and submit a pull request with your implementation. Thanks :)
